# site properties and page defaults
title: Interactive Media Technology Lab
subtitle: Nuremberg Institute of Technology
description: Dive into the future of interactive media with us at the Interactive Media Technology Lab! We're crafting the next generation of digital experiences, where innovation meets immersion.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: thomas.chang@th-nuernberg.de
  orcid: 0009-0008-9033-1298
  google-scholar: 7u8Y5k0AAAAJ
  github: changtvs
  youtube: ThomasVChang

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
