# HHTS
- id: 10.1109/CVPR52733.2024.00308
  image: images/hhts-teaser.jpg
  buttons:
  - type: source
    text: Code
    link: https://github.com/changtvs/HHTS
  - type: website
    text: Project Page
    link: https://changtvs.github.io/hierarchical-histogram-threshold-segmentation/
  tags:
    - Computer Vision
    - Oversegmentation

# DGSI
- id: 10.2312/egp.20241038
  image: images/dgsi-teaser.jpg
  tags:
    - Computer Vision
    - Computer Graphics
    - Novel View Synthesis

# DFM4SfM
- id: 10.1109/ICIPC59416.2023.10328368
  image: images/dfm4sfm-teaser.jpg
  tags:
    - Computer Vision
    - Structure from Motion